# Site Configuration
title: Computer Organization
tagline: In piles, on shelves...
base:
  
# Server Config
auto: true
permalink: /:categories/:year/:month/:day/:title

# My Config
phone: 925-238-3692
officehours: M 9:30-11:30, T 13:30-15:30, by appt.
short: CompOrg
designation: CSC 435
prof_url: http://www.berea.edu/csc/matt-jadud/